import * as React from "react";
import Box from "@mui/material/Box";
import {DataGrid} from "@mui/x-data-grid";

const columns = [
    {
        field: "assignorDepartment",
        headerName: "Generated By",
        minWidth: 150,
        sortable: false,
        disableColumnMenu: true,
        headerClassName: "theme--header",
        flex: 3,
        align: 'center',
        headerAlign: 'center',
    },
    {
        field: "client_name",
        headerName: "Client Name",
        minWidth: 150,
        sortable: false,
        disableColumnMenu: true,
        headerClassName: "theme--header",
        flex: 3,
        align: 'center',
        headerAlign: 'center',

    },
    {
        field: "majorAssignee",
        headerName: "Assigned For",
        minWidth: 150,
        sortable: false,
        disableColumnMenu: true,
        headerClassName: "theme--header",
        flex: 3,
        align: 'center',
        headerAlign: 'center',

    },
    {
        field: "user_name",
        headerName: "By User",
        maxWidth: 80,
        sortable: false,
        disableColumnMenu: true,
        headerClassName: "theme--header",
        flex: 3,
        align: 'center',
        headerAlign: 'center',

    },
    {
        field: "createdAt",
        headerName: "Date of Creation",
        type: "number",
        minWidth: 150,
        sortable: false,
        disableColumnMenu: true,
        headerClassName: "theme--header",
        align: 'center',
        headerAlign: 'center',
        flex: 3,
        valueGetter: ({row}) => new Date(row.createdAt).toDateString()
    },
    {
        field: "dueDate",
        headerName: "Due Date",
        sortable: false,
        disableColumnMenu: true,
        headerClassName: "theme--header",
        flex: 3,
        minWidth: 200,
        align: 'center',
        headerAlign: 'center',
        valueGetter: ({row}) => new Date(row.dueDate).toDateString(),
    },
];

export default function NotificationGrid({rows}) {
    return (
        <Box sx={{height: 400, width: "100%"}}>
            <DataGrid
                disableRowSelectionOnClick
                getRowId={(row) => row._id}
                rows={rows}
                columns={columns}
                initialState={{
                    pagination: {
                        paginationModel: {
                            pageSize: 5,
                        },
                    },
                }}
                pageSizeOptions={[5]}
                sx={{
                    "& .theme--header": {
                        backgroundColor: "primary.main",
                        display: "flex",
                        color: "white",
                        border: "none !important",
                        outline: "none !important",
                        fontSize: "0.9rem",
                    },
                    "& .MuiDataGrid-columnSeparator": {
                        display: "none",
                    },
                }}
            />
        </Box>
    );
}
